config/routes.rb
CoffeeCup::Application.routes.draw do

  devise_for :administrators, :path => '', :path_names => {:sign_in => 'sign-in', :sign_out => 'sign-out'}

  namespace :administration do

    resources :posts
  end

  root to: "home#show"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(administrator = nil)

    if administrator
      can :manage, Post
    else
      can :read, :all
    end
  end
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true

  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :administrator

  validates :title, :body, :administrator, presence: true

  def author
    administrator.username
  end
end

app/controllers/administration/base_controller.rb
class Administration::BaseController < ApplicationController
  before_action :authenticate_administrator!

  layout 'administration'
end

app/controllers/administration/posts_controller.rb
class Administration::PostsController < Administration::BaseController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new()
  end

  def create
    authorize! :create, Post

    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to action: 'index', notice: 'Post successfully created' }
      else
        format.html { render 'new' }
      end
    end
  end

  private

  def post_params
    params[:post].permit!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_ability
    @current_ability ||= Ability.new(current_administrator)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def create
    authorize! :create, Post

    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to action: 'index', notice: 'Post successfully created' }
      else
        format.html { render 'new' }
      end
    end
  end

  private

  def post_params
    params[:post].permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/administration/posts/index.html.erb
<h1>The post index</h1>

<% @posts.each do |post| %>
  <%= post.title %>
<% end %>

app/views/administration/posts/new.html.erb
<h1>Made it</h1>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>
<%= link_to 'Sign in', new_administrator_session_path %>

app/views/layouts/administration.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">
        <p class="notice"><%#= notice %></p>
        <p class="alert"><%#= alert %></p>

        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">
        <p class="notice"><%#= notice %></p>
        <p class="alert"><%#= alert %></p>

        <%= yield %>
      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>